[BLD]
init_freq = 1000
init_duty = 0
min_freq = 100
max_freq = 10_000
min_duty = 0
max_duty = 1023
min_timer = 100
max_timer = 10_000
init_timer = 1000
eta_update_interval = 50

[RLD]
init_freq = 1000
init_duty = 0
min_freq = 100
max_freq = 10_000
min_duty = 0
max_duty = 1023
min_timer = 100
max_timer = 10_000
init_timer = 1000
eta_update_interval = 50

[Listener]
polling_interval = 200
