[data]

	[data.time]
	format_string = ".3f"
	units = "s"
	in_file = true

	[data.temperature]
	format_string = ".3f"
	units = "K"
	in_file = true

	[data.temp_rate]
	format_string = ".3f"
	units = "K/min"
	in_file = true
	init_value = 1.0

	[data.temp_sp]
	format_string = ".3f"
	units = "K"
	in_file = true
	init_value = 300.0

	[data.temp_target]
	format_string = ".3f"
	units = "K"
	in_file = true
	init_value = 300.0

	[data.heater_power]
	format_string = ".3f"
	units = "W"
	in_file = true
	init_value = 0.0

	[data.heater_power_output]
	format_string = ".3f"
	units = "W"
	in_file = true
	init_value = 0.0

	[data.heater_power_prop]
	format_string = ".3f"
	units = "W"
	in_file = true
	init_value = 0.0

	[data.heater_power_int]
	format_string = ".3f"
	units = "W"
	in_file = true
	init_value = 0.0

	[data.heater_power_diff]
	format_string = ".3f"
	units = "W"
	in_file = true
	init_value = 0.0

	[data.heater_PID_Kp]
	format_string = ".2f"
	units = "W/K"
	in_file = true
	init_value = 5.0

	[data.heater_PID_Ki]
	format_string = ".2f"
	units = "W/(K*min)"
	in_file = true
	init_value = 3.0

	[data.heater_PID_Kd]
	format_string = ".2f"
	units = "W*min/K"
	in_file = true
	init_value = 1.0

	# [data.diff_pressure]
	# format_string = ".2e"
	# units = "mbar"
	# in_file = true

	# [data.diff_pressure_rate]
	# format_string = ".2e"
	# units = "mbar/s"
	# in_file = true

	# [data.he_chamber_flow]
	# format_string = ".2e"
	# units = "ml/s"
	# in_file = true

	# [data.sample_chamber_flow]
	# format_string = ".2e"
	# units = "ml/s"
	# in_file = true

	# [data.valve_reostat_resistance]
	# format_string = ".2e"
	# units = "ml/s"
	# in_file = true

	# [data.valve_position]
	# format_string = ".2e"
	# units = "ml/s"
	# in_file = true
	# init_value = 0.0

	# [data.valve_pos_output]
	# format_string = ".3f"
	# units = "°"
	# in_file = true
	# init_value = 0.0

	# [data.valve_pos_prop]
	# format_string = ".3f"
	# units = "°"
	# in_file = true
	# init_value = 0.0

	# [data.valve_pos_int]
	# format_string = ".3f"
	# units = "°"
	# in_file = true
	# init_value = 0.0

	# [data.valve_pos_diff]
	# format_string = ".3f"
	# units = "°"
	# in_file = true
	# init_value = 0.0

	# [data.valve_PID_Kp]
	# format_string = ".2f"
	# units = "°/(L/min)"
	# in_file = true
	# init_value = 5.0

	# [data.valve_PID_Ki]
	# format_string = ".2f"
	# units = "°/(min*(L/min))"
	# in_file = true
	# init_value = 3.0

	# [data.valve_PID_Kd]
	# format_string = ".2f"
	# units = "°*min/(L/min)"
	# in_file = true
	# init_value = 1.0

[history]
max_points_count = 10000

[temp_controller]
default_rate = 1

[heater]
pwm_resolution = 13
max_power = 10.6
max_frequency = 30000

[flow_controller]
min_position = 0
max_position = 360

[thermometer]
cal_path = 'thermometry\calibration_curves\Si_diode_calibration.dat'

[instruments]
	
	[instruments.k2000]
	baud_rate = 4800
	write_termination = "\r"
	read_termination = "\r"
	timeout = 1000
	meas_command = "MEAS:DIOD?"
	range_command = "DIOD:CURR:RANG 0.0001"

[datafile]
column_separator = "\t"

[gui]

	[gui.preview]
	default_row_count = 2
	default_column_count = 2
	max_points_count = 5000
